name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Test Module with Pester
      shell: pwsh
      run: |
        # Install Pester module explicitly to ensure version used in tests
        Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        
        # Run tests
        $config = New-PesterConfiguration
        $config.Run.Path = "Tests/Monitor.Tests.ps1"
        $config.Output.Verbosity = "Detailed"
        $config.CodeCoverage.Enabled = $true
        Invoke-Pester -Configuration $config
